name: Storage CDN CI/CD

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/BlazorWasmStorage/*
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/BlazorWasmStorage/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use DotNet 6'
    inputs:
      version: '6.0.300'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/BlazorWasmStorage.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/BlazorWasmStorage.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      projects: '**/BlazorWasmStorage.csproj'
      publishWebProjects: false
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

  - task: AzureFileCopy@3
    displayName: 'Deploy AzureBlob'
    inputs:
      SourcePath: '$(build.artifactstagingdirectory)/wwwroot'
      azureSubscription: ANPBlazorAzure
      Destination: AzureBlob
      storage: blazorstorageanp
      ContainerName: '$web'
      sasTokenTimeOutInMinutes: 240

  - task: AzureCLI@2
    displayName: 'Azure CDN Cache '
    inputs:
      azureSubscription: ANPBlazorAzure
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: 'az cdn endpoint purge -g ANP_Blazor -n blazor-static-anp --profile-name blazor-static-anp --content-paths "/*'